version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: woxa_db
    restart: always
    environment:
      POSTGRES_USER: woxa_user
      POSTGRES_PASSWORD: woxa_password123
      POSTGRES_DB: woxa_db
    ports:
      - "5433:5432"   # ← ไม่ต้องแก้ครับ ใช้ 5433 ได้เลย
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - woxa_network
    healthcheck:                          # ← เพิ่มตรงนี้!
      test: ["CMD-SHELL", "pg_isready -U woxa_user -d woxa_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: woxa_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - woxa_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./crud-backend
      dockerfile: Dockerfile
    container_name: woxa_backend
    restart: always
    environment:
      DB_HOST: postgres       # ← ใน Docker ใช้ชื่อ service
      DB_PORT: 5432           # ← ใน Docker network ใช้ 5432 (internal port)
      DB_USERNAME: woxa_user
      DB_PASSWORD: woxa_password123
      DB_NAME: woxa_db
      JWT_SECRET: your_super_secret_jwt_key_here
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL_SECONDS: 3600
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - woxa_network


  frontend:
    build:
      context: ./crud-frontend
      dockerfile: Dockerfile
    container_name: woxa_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend       # ← รอ backend ขึ้นก่อน
    networks:
      - woxa_network    

volumes:
  postgres_data:

networks:
  woxa_network:
    driver: bridge